name: Daily Commit

on:
  workflow_dispatch:  # Enable manual trigger
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Make a commit
        run: |
          echo "Daily commit on $(date)" >> daily_commit.txt
          git config --local user.email "talhaatif@gmail.com"
          git config --local user.name "talha atif"
          git add daily_commit.txt
          
          # Check for changes before committing
          if ! git diff --cached --quiet; then
            git commit -m "Daily commit on $(date '+%Y-%m-%d %H:%M:%S')"
          else
            echo "No changes to commit"
            exit 0
          fi

          # Fetch and merge changes from the remote before pushing
          git fetch origin main
          git merge origin/main --no-edit

          # Push using the PAT
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Progambler227788/KOTLIN-.git
