name: Daily Commit

# Allow manual triggering using workflow_dispatch
on:
  workflow_dispatch:  # This enables manual execution of the workflow
  schedule:
    - cron: '0 0 * * *'  # This runs at 00:00 UTC every day

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the code from your repository
      
      - name: Make a commit
        run: |
          echo "Daily commit on $(date)" >> daily_commit.txt
          git config --local user.email "talha@gmail.com"
          git config --local user.name "talha"
          git add daily_commit.txt
          git commit -m "Daily commit on $(date '+%Y-%m-%d %H:%M:%S')"
          git push
